require("plugins.coc")
require("plugins.comment")
require("plugins.null-ls")
require("plugins.nvim-tree")
require("plugins.telescope")
require('toggle_lsp_diagnostics').init()
require("plugins.avante")
require("plugins.markview")
